AllCops:
  Include:
    - 'lib/**/*.rb'
  Exclude:
    - '*.rb'
    - 'spec/**/*'
    - 'features/**/*'
    - 'test/**/*'

FileName:
  Exclude:
    - 'Gemfile'
    - 'Rakefile'

Metrics/ClassLength:
  Max: 150

MethodLength:
  Max: 30

Documentation:
  Enabled: false

AndOr:
  Enabled: false

ParenthesesAroundCondition:
  Enabled: false

MethodCallWithoutArgsParentheses:
  Enabled: false

# why use this option ?
#RedundantBegin:
#  Enabled: false

NumericLiterals:
  Enabled: false

CyclomaticComplexity:
  Max: 15

Next:
  Enabled: false

Layout/AlignHash:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/RedundantFreeze:
  Enabled: false

Metrics/AbcSize:
  Max: 18

Metrics/LineLength:
  Max: 100
  IgnoredPatterns: [
    '^\s*#'
  ]

Style/FileName:
  Enabled: false

Lint/RescueWithoutErrorClass:
  Enabled: false
